"""Add role_id to account table

Revision ID: 5d80ee64afcf
Revises: d3c167b9b896
Create Date: 2025-02-21 17:18:38.689935

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d80ee64afcf"
down_revision = "d3c167b9b896"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
