"""Add delete_flag and deleted_at for acccount

Revision ID: 90a0dcd1f8e6
Revises: 5d80ee64afcf
Create Date: 2025-02-21 23:34:47.902024

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "90a0dcd1f8e6"
down_revision = "5d80ee64afcf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("delete_flag", sa.Boolean(), nullable=False))
    op.add_column(
        "account", sa.Column("deleted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "deleted_at")
    op.drop_column("account", "delete_flag")
    # ### end Alembic commands ###
